name: MoneyPouch
main: MoneyPouch\Main
version: 1.0
api: [3.0.0-ALPHA10, 3.0.0-ALPHA11]
author: TastySandwich, MangoTheDev
description: MoneyPouch
commands:
 moneypouch:
  description: "Give a money pouch"
